import { View, Text, ScrollView, RefreshControl, TouchableOpacity, Alert, Linking, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useQuery } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { useAuthStore, useThemeStore } from '@/stores';
import { billingService } from '@/services';
import { LoadingScreen, EmptyState, ScreenHeader, Badge } from '@/shared/components/ui';
import { formatCurrency } from '@/shared/utils/format';
import type { BillingStatement } from '@/shared/types';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function BillingScreen() {
  const profile = useAuthStore((s) => s.profile)!;
  const dark = useThemeStore((s) => s.dark);

  const { data: statements, isLoading, refetch, isRefetching } = useQuery({
    queryKey: ['billing', profile.id],
    queryFn: () => billingService.getByCustomer(profile.id),
  });

  const bg = dark ? '#0F1A0A' : '#F5F9F2';
  const cardBg = dark ? '#243018' : '#FFFFFF';
  const border = dark ? '#2D3D22' : '#E8F0E2';
  const text = dark ? '#E8F5E0' : '#1A2614';
  const muted = dark ? '#8FA882' : '#5A6B52';

  const pendingTotal = statements?.reduce((sum, s) => sum + s.pendingAmount, 0) ?? 0;
  const paidTotal = statements?.reduce((sum, s) => sum + s.paidAmount, 0) ?? 0;

  const downloadPdf = async (stmt: BillingStatement) => {
    if (!stmt.pdfUrl) {
      Alert.alert('PDF Not Ready', 'Your bill PDF will be available once generated by admin.');
      return;
    }
    try {
      await Linking.openURL(stmt.pdfUrl);
    } catch {
      Alert.alert('Error', 'Could not open PDF');
    }
  };

  if (isLoading) return <LoadingScreen />;

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: bg }}>
      <ScreenHeader title="Billing" subtitle="Monthly statements & payments" gradient />
      <ScrollView
        contentContainerStyle={{ padding: 16, paddingBottom: 32 }}
        refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} colors={['#1E5C0A']} tintColor="#1E5C0A" />}
      >
        <View style={{ flexDirection: 'row', gap: 12, marginBottom: 20 }}>
          <View style={[styles.summaryCard, { backgroundColor: cardBg, borderColor: border, flex: 1 }]}>
            <Text style={{ color: muted, fontSize: 12, fontWeight: '600' }}>Pending</Text>
            <Text style={{ fontSize: 22, fontWeight: '800', color: '#DC2626', marginTop: 4 }}>{formatCurrency(pendingTotal)}</Text>
          </View>
          <View style={[styles.summaryCard, { backgroundColor: cardBg, borderColor: border, flex: 1 }]}>
            <Text style={{ color: muted, fontSize: 12, fontWeight: '600' }}>Paid</Text>
            <Text style={{ fontSize: 22, fontWeight: '800', color: '#16A34A', marginTop: 4 }}>{formatCurrency(paidTotal)}</Text>
          </View>
        </View>

        <Text style={{ fontSize: 16, fontWeight: '700', color: text, marginBottom: 12 }}>Statement History</Text>

        {!statements?.length ? (
          <EmptyState title="No statements" message="Monthly bills will appear here after delivery." icon="💰" />
        ) : (
          statements.map((stmt) => (
            <View key={stmt.id} style={[styles.card, { backgroundColor: cardBg, borderColor: border }]}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <View>
                  <Text style={{ fontWeight: '800', color: text, fontSize: 15 }}>
                    {MONTHS[stmt.month - 1]} {stmt.year}
                  </Text>
                  <Text style={{ color: muted, fontSize: 12, marginTop: 2 }}>
                    {stmt.orderIds?.length ?? 0} orders
                  </Text>
                </View>
                <Badge
                  label={stmt.paymentStatus}
                  color={stmt.paymentStatus === 'paid' ? 'success' : stmt.paymentStatus === 'partial' ? 'warning' : 'error'}
                />
              </View>
              <View style={[styles.row, { borderColor: border }]}>
                <Text style={{ color: muted }}>Total: {formatCurrency(stmt.totalAmount)}</Text>
                <Text style={{ color: '#DC2626', fontWeight: '700' }}>Due: {formatCurrency(stmt.pendingAmount)}</Text>
              </View>
              {stmt.pdfUrl && (
                <TouchableOpacity onPress={() => downloadPdf(stmt)} style={styles.pdfBtn}>
                  <Ionicons name="download-outline" size={16} color="#1A7BBE" />
                  <Text style={{ color: '#1A7BBE', fontWeight: '600', marginLeft: 6, fontSize: 13 }}>Download PDF</Text>
                </TouchableOpacity>
              )}
            </View>
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  summaryCard: { borderRadius: 14, padding: 16, borderWidth: 1 },
  card: { borderRadius: 14, padding: 14, borderWidth: 1, marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, paddingTop: 10, borderTopWidth: 1 },
  pdfBtn: { flexDirection: 'row', alignItems: 'center', marginTop: 10, paddingTop: 10 },
});
